
# CREATE
POST http://localhost:8080/person HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "surName": "Doe",
  "dateOfBirth": "1980-01-01"
}

###
# UPDATE
PUT http://localhost:8080/person/4 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Johnny"
}
###
# DELETE
DELETE http://localhost:8080/person/3 HTTP/1.1

# GET
GET http://localhost:8080/person/4 HTTP/1.1
